# Generated by Django 4.1.3 on 2023-06-12 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200, verbose_name='주문 당시 상품명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='주문 당시 상품가격')),
                ('status', models.CharField(choices=[('PAYMENT.WAIT', '결제대기'), ('PAYMENT.COMPLETE', '결제완료'), ('DELIVERY.WAIT', '배송준비중'), ('DELIVERY.IN', '배송중'), ('DELIVERY.COMPLETE', '배송완료'), ('ORDER.CANCEL', '주문취소'), ('ORDER.SOLDOUT', '품절')], default='PAYMENT.WAIT', max_length=45, verbose_name='주문 상태')),
                ('delivery_started_at', models.DateTimeField(default=None, null=True, verbose_name='배송시작일')),
                ('delivery_finished_at', models.DateTimeField(default=None, null=True, verbose_name='배송종료일')),
                ('product', models.ManyToManyField(db_constraint=False, related_name='orders', to='products.product')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
    ]
