# Generated by Django 4.1.3 on 2023-06-13 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 주문 가격')),
                ('status', models.CharField(choices=[('ORDER.NONE', '대기'), ('PAYMENT.WAIT', '결제대기'), ('PAYMENT.COMPLETE', '결제완료'), ('ORDER.CANCEL', '주문취소'), ('ORDER.SOLDOUT', '품절')], default='ORDER.NONE', max_length=45, verbose_name='주문 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='주문 당시 상품명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='주문 당시 상품가격')),
                ('qty', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ORDER.NONE', '대기'), ('DELIVERY.WAIT', '배송준비중'), ('DELIVERY.IN', '배송중'), ('DELIVERY.COMPLETE', '배송완료'), ('PRODUCT.SOLDOUT', '품절')], default='ORDER.NONE', max_length=45, verbose_name='주문 상태')),
                ('delivery_started_at', models.DateTimeField(default=None, null=True, verbose_name='배송시작일')),
                ('delivery_finished_at', models.DateTimeField(default=None, null=True, verbose_name='배송종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'db_table': 'order_products',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderProduct', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
