# Generated by Django 4.1.3 on 2023-06-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='주문 당시 상품가격'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
